"""Decision rules for confirming/vetoing existing bot signals.

Layered, matching the priority order for scalping:
1. Microstructure (primary): gates the confirm/neutral/veto decision when
   fresh, good-quality market data is available.
2. Sentiment (secondary): only nudges the confidence modifier; it can never
   flip a microstructure decision.
3. Fallback: without usable microstructure, the original sentiment-only rules
   apply unchanged (and lean neutral without data).

The engine never generates a new trade. It only confirms, stays neutral, or
vetoes a signal generated by the trading bot.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Optional, Tuple

from sentiment_engine.config import (
    ATTENTION_SPIKE_CONFIRM,
    MAX_CONFIDENCE_BOOST,
    MAX_CONFIDENCE_REDUCTION,
    MICRO_CONFIRM_SCORE,
    MICRO_MAX_SPREAD_BPS,
    MICRO_MIN_DEPTH_QUOTE,
    MICRO_QUALITY_MIN,
    MICRO_VETO_SCORE,
    MICRO_VOL_BURST_BPS,
    MIN_DATA_QUALITY,
    NEUTRAL_CONFIDENCE_MODIFIER,
    SENTIMENT_MODIFIER_STEP,
    SENTIMENT_VELOCITY_CONFIRM,
    SENTIMENT_VELOCITY_VETO,
)
from sentiment_engine.signals.micro_quality import micro_direction_score, micro_quality_score
from sentiment_engine.signals.price_divergence import contradicts_direction
from sentiment_engine.types import (
    MicrostructureSnapshot,
    SentimentAction,
    SentimentSnapshot,
    TradeDirection,
    TradeEvaluation,
)


def clamp_decimal(value: Decimal, low: Decimal, high: Decimal) -> Decimal:
    return max(low, min(high, value))


def _build(
    *,
    snapshot: SentimentSnapshot,
    action: SentimentAction,
    modifier: Decimal,
    bot_confidence: Decimal,
    data_quality: Decimal,
    reason: str,
    safe_to_use: bool,
) -> TradeEvaluation:
    return TradeEvaluation(
        symbol=snapshot.symbol,
        action=action,
        sentiment_score=snapshot.average_sentiment,
        confidence_modifier=modifier,
        final_confidence_estimate=clamp_decimal(bot_confidence * modifier, Decimal("0"), Decimal("1")),
        data_quality=data_quality,
        reason=reason,
        safe_to_use=safe_to_use,
        snapshot=snapshot,
    )


# --- layer 2: sentiment as a confidence nudge ------------------------------

def _sentiment_adjustment(snapshot: SentimentSnapshot, direction: TradeDirection) -> Tuple[Decimal, str]:
    """(modifier delta, note). Zero when social data is unusable."""
    if snapshot.data_quality < MIN_DATA_QUALITY:
        return Decimal("0"), "sentiment unavailable"
    velocity = snapshot.sentiment_velocity
    aligned = (direction is TradeDirection.LONG and velocity >= SENTIMENT_VELOCITY_CONFIRM) or (
        direction is TradeDirection.SHORT and velocity <= -SENTIMENT_VELOCITY_CONFIRM
    )
    contradicting = contradicts_direction(direction, velocity) and abs(velocity) >= SENTIMENT_VELOCITY_VETO
    if aligned:
        return SENTIMENT_MODIFIER_STEP, f"sentiment aligned (velocity={velocity})"
    if contradicting:
        return -SENTIMENT_MODIFIER_STEP, f"sentiment contradicts (velocity={velocity})"
    return Decimal("0"), "sentiment neutral"


# --- layer 1: microstructure decision ---------------------------------------

def _evaluate_with_micro(
    *,
    snapshot: SentimentSnapshot,
    direction: TradeDirection,
    bot_confidence: Decimal,
    micro: MicrostructureSnapshot,
    micro_quality: float,
) -> TradeEvaluation:
    quality = Decimal(str(micro_quality))

    # Regime gates: bad scalping conditions veto regardless of direction.
    if micro.spread_bps is not None and micro.spread_bps > MICRO_MAX_SPREAD_BPS:
        return _build(
            snapshot=snapshot,
            action=SentimentAction.VETO,
            modifier=MAX_CONFIDENCE_REDUCTION,
            bot_confidence=bot_confidence,
            data_quality=quality,
            reason=(
                f"Veto: spread {micro.spread_bps:.2f} bps exceeds scalp limit "
                f"{MICRO_MAX_SPREAD_BPS} bps."
            ),
            safe_to_use=True,
        )

    confirm_blocked = False
    gate_note = ""
    if micro.volatility_bps_30s is not None and micro.volatility_bps_30s > MICRO_VOL_BURST_BPS:
        depth = (micro.bid_depth_quote or 0.0) + (micro.ask_depth_quote or 0.0)
        if MICRO_MIN_DEPTH_QUOTE > 0 and depth < MICRO_MIN_DEPTH_QUOTE:
            return _build(
                snapshot=snapshot,
                action=SentimentAction.VETO,
                modifier=MAX_CONFIDENCE_REDUCTION,
                bot_confidence=bot_confidence,
                data_quality=quality,
                reason=(
                    f"Veto: volatility burst {micro.volatility_bps_30s:.1f} bps with thin book "
                    f"(depth {depth:.0f} < {MICRO_MIN_DEPTH_QUOTE:.0f})."
                ),
                safe_to_use=True,
            )
        confirm_blocked = True
        gate_note = f" Confirm blocked: volatility burst {micro.volatility_bps_30s:.1f} bps."

    score = micro_direction_score(micro)
    if score is None:
        return _build(
            snapshot=snapshot,
            action=SentimentAction.NEUTRAL,
            modifier=NEUTRAL_CONFIDENCE_MODIFIER,
            bot_confidence=bot_confidence,
            data_quality=quality,
            reason="Neutral: no directional microstructure score available." + gate_note,
            safe_to_use=True,
        )

    directional = score if direction is TradeDirection.LONG else -score

    if directional <= -MICRO_VETO_SCORE:
        action = SentimentAction.VETO
        base_modifier = MAX_CONFIDENCE_REDUCTION
        verdict = (
            f"Veto: microstructure score {score:+.4f} contradicts {direction.value} "
            f"(threshold {MICRO_VETO_SCORE})."
        )
    elif directional >= MICRO_CONFIRM_SCORE and not confirm_blocked:
        action = SentimentAction.CONFIRM
        base_modifier = Decimal("1.05")
        verdict = (
            f"Confirm: microstructure score {score:+.4f} aligns with {direction.value} "
            f"(threshold {MICRO_CONFIRM_SCORE})."
        )
    else:
        action = SentimentAction.NEUTRAL
        base_modifier = NEUTRAL_CONFIDENCE_MODIFIER
        verdict = f"Neutral: microstructure score {score:+.4f} below thresholds for {direction.value}."

    # Sentiment only nudges confidence; it never flips the action.
    adjustment, note = _sentiment_adjustment(snapshot, direction)
    modifier = clamp_decimal(base_modifier + adjustment, MAX_CONFIDENCE_REDUCTION, MAX_CONFIDENCE_BOOST)

    return _build(
        snapshot=snapshot,
        action=action,
        modifier=modifier,
        bot_confidence=bot_confidence,
        data_quality=quality,
        reason=f"{verdict}{gate_note} [{note}; micro_quality={micro_quality}]",
        safe_to_use=True,
    )


# --- fallback: original sentiment-only rules --------------------------------

def _evaluate_sentiment_only(
    *,
    snapshot: SentimentSnapshot,
    direction: TradeDirection,
    bot_confidence: Decimal,
) -> TradeEvaluation:
    if snapshot.data_quality < MIN_DATA_QUALITY:
        return _build(
            snapshot=snapshot,
            action=SentimentAction.NEUTRAL,
            modifier=NEUTRAL_CONFIDENCE_MODIFIER,
            bot_confidence=bot_confidence,
            data_quality=snapshot.data_quality,
            reason=(
                f"Neutral: no usable microstructure and social data quality "
                f"{snapshot.data_quality} below minimum {MIN_DATA_QUALITY}. "
                f"messages={snapshot.message_count}"
            ),
            safe_to_use=False,
        )

    velocity = snapshot.sentiment_velocity
    attention = snapshot.attention_spike

    confirms_long = direction is TradeDirection.LONG and velocity >= SENTIMENT_VELOCITY_CONFIRM
    confirms_short = direction is TradeDirection.SHORT and velocity <= -SENTIMENT_VELOCITY_CONFIRM
    confirms = (confirms_long or confirms_short) and attention >= ATTENTION_SPIKE_CONFIRM
    vetoes = (
        contradicts_direction(direction, velocity)
        and abs(velocity) >= SENTIMENT_VELOCITY_VETO
        and attention >= ATTENTION_SPIKE_CONFIRM
    )

    if vetoes:
        return _build(
            snapshot=snapshot,
            action=SentimentAction.VETO,
            modifier=MAX_CONFIDENCE_REDUCTION,
            bot_confidence=bot_confidence,
            data_quality=snapshot.data_quality,
            reason=(
                f"Veto: sentiment velocity {velocity} contradicts {direction.value} "
                f"while attention spike is {attention}."
            ),
            safe_to_use=True,
        )
    if confirms:
        return _build(
            snapshot=snapshot,
            action=SentimentAction.CONFIRM,
            modifier=MAX_CONFIDENCE_BOOST,
            bot_confidence=bot_confidence,
            data_quality=snapshot.data_quality,
            reason=(
                f"Confirm: sentiment velocity {velocity} aligns with {direction.value} "
                f"and attention spike is {attention}."
            ),
            safe_to_use=True,
        )
    return _build(
        snapshot=snapshot,
        action=SentimentAction.NEUTRAL,
        modifier=NEUTRAL_CONFIDENCE_MODIFIER,
        bot_confidence=bot_confidence,
        data_quality=snapshot.data_quality,
        reason=(
            f"Neutral: no strong actionable sentiment. velocity={velocity}, "
            f"attention={attention}, direction={direction.value}."
        ),
        safe_to_use=True,
    )


# --- entry point -------------------------------------------------------------

def evaluate_trade_signal(
    *,
    snapshot: SentimentSnapshot,
    direction: TradeDirection,
    bot_confidence: Decimal,
    micro: Optional[MicrostructureSnapshot] = None,
    micro_stale: bool = True,
) -> TradeEvaluation:
    """Evaluate an existing bot signal. Returns confirm/neutral/veto only."""
    quality = micro_quality_score(micro, micro_stale)
    if micro is not None and not micro_stale and quality >= MICRO_QUALITY_MIN:
        return _evaluate_with_micro(
            snapshot=snapshot,
            direction=direction,
            bot_confidence=bot_confidence,
            micro=micro,
            micro_quality=quality,
        )
    return _evaluate_sentiment_only(
        snapshot=snapshot,
        direction=direction,
        bot_confidence=bot_confidence,
    )
